### ISSUE TITLE
Discussion Draft

### ISSUE THREAD

**Issue by annarupert** [ecn310/course-project-accidentsteam#20]
Here is a place to put your finished draft @Yuhan-2435

**Comment by annarupert** [comment]
@Yuhan-2435 Please let me know how far you get in the discussion today! I am going to add all that I have to our submission.

**Comment by Yuhan-2435** [comment]
The data analysis and results above display that there are potential issues existed within the dataset. The data collected by OSHA are self-reports of number of incidents from individual firms. The different policies that each firm has on reporting and defining an accident may lead to the outliers in variables studied. And there is no obvious way to avoid these extreme cases for data collections. To continue the research, exploring on new data resources which contain the accidents report for different types and size of firm may resolve the unnormal cases. In addition, it is also worth studying about the variable of total_respiratory_condition. In the year case of 2023, this variable has an unusual rate of respiration related accidents per capita, which may be due to the aftermath of COVID-19. In future study, a deeper exploration on the total_respiratory_condition in the year case of 2019, 2020, 2021, 2022 is necessary to check on the influence of COVID-19. And by studying the injuries rate in these year cases, it helps determine the correlations on the external factors and the injuries rate per capita, firm size.

**Comment by annarupert** [comment]
#Discussion

The data analysis and results above display that there are potential issues existed within the data set. The data collected by OSHA are self-reports of number of incidents from individual firms. The different policies that each firm has on reporting and defining an accident may lead to the outliers in variables studied. And there is no obvious way to avoid these extreme cases for data collections. To continue the research, exploring on new data resources which contain the accidents report for different types and size of firm may resolve the abnormal cases. In addition, it is also worth studying about the variable of total\_respiratory\_condition. In the year case of 2023, this variable has an unusual rate of respiration related accidents per capita, which may be due to the aftermath of COVID-19. In future study, a deeper exploration on the total\_respiratory\_condition in the year case of 2019, 2020, 2021, 2022 is necessary to check on the influence of COVID-19. And by studying the injuries rate in these year cases, it helps determine the correlations on the external factors and the injuries rate per capita, firm size.


Feed Back:
This section needs much more careful proofreading, but otherwise is largely fine. I just can't figure out what you're trying to convey with

"And by studying the injuries rate in these year cases, it helps determine the correlations on the external factors and the injuries rate per capita, firm size."

**Comment by Yuhan-2435** [comment]
The data analysis and results above display that there are potential issues within the dataset. The data collected by OSHA are self-reports of the number of accidents from individual establishments. The different policies that each establishment has on reporting and defining an accident may lead to the outliers in variables studied. And there is no obvious way to avoid these extreme cases for data collection. To continue the research, exploring new data sources that contain accident reports for different types and sizes of establishments may resolve these abnormal cases. In addition, it is also worth studying the variable of total respiratory condition. In the year case of 2023, this variable has an exceptional rate of respiration-related accidents per capita, which may be due to the aftermath of COVID-19. In future studies, a deeper exploration of the total_respiratory_condition in the year cases of 2019, 2020, 2021, and 2022 is necessary to check on the influence of COVID-19.

**Comment by annarupert** [comment]
Thank you !!!
